### ISSUE TITLE
Agent Docs - more definitions and helpful FAQs

### ISSUE THREAD

**Issue by TrevorJTClarke** [Cron-Near/docs#14]
Agent fees & rewards - how much min balance, autowithdraw, etc
- how to run multiple agents in one machine
- "Pending" status, and how to read the stats page

**Comment by grodstrike** [comment]
I started the FAQ here, I will add new questions and answers:
https://github.com/Cron-Near/docs/blob/main/content/docs/agent-faq.md

**Comment by sicmundu** [comment]
Added:

- how to run multiple agents
- how to read croncat status
- how to update croncat agent cli

**Comment by sicmundu** [comment]
#18
