### ISSUE TITLE
How to run validator + croncat

### ISSUE THREAD

**Issue by TrevorJTClarke** [Cron-Near/docs#17]
For each network:
* Mainnet
* Testnet
* Guildnet

Basic gist:
- Basic needs: server, nearcore
- Links on where to get each network validator setup
- Once keys and validator are running show how to setup your ping script
- Then show how to setup croncat CLI to become an agent within a "screen" instance including how to observe logs
- Can also show how to configure monitoring on the croncat CLI

**Comment by TrevorJTClarke** [comment]
https://github.com/grodstrike/NEAR-Validator-Tools/blob/main/ping_install.sh
Amazing script! Just need a doc page now... ;D

**Comment by grodstrike** [comment]
Done!
https://github.com/Cron-Near/docs/blob/main/content/docs/validator-croncat.md
